# Generated by Django 4.1.7 on 2023-03-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Surname',
        ),
    ]
